version: "3"
services:
  turnserver:
    image: "coturn/coturn:4.5.2"
    network_mode: "host"
    command: ["-a", "-v", "-n", "-u", "user:password", "-p", "3578", "-r", "default-realm", "--no-dtls", "--no-tls"]
    init: true

  signalling:
    image: "pixel-streaming-signalling-server:latest"
    network_mode: "host"
    command:
      - "--publicIp=18.163.87.20"
      - "--peerConnectionOptions={\"iceServers\":[{\"urls\": [\"stun:stun.l.google.com:19302\"]}, {\"urls\": [\"turn:18.163.87.20:3478\"], \"username\": \"user\", \"credential\": \"password\"}]}"
    init: true
    depends_on:
      - turnserver

  project:
    image: "pixel-streaming-example/project:latest"
    network_mode: "host"
    command:
      - "-RenderOffscreen"
      - "-Windowed"
      - "-ForceRes"
      - "-ResX=1920"
      - "-ResY=1080"
      - "-PixelStreamingIP=18.163.87.20"
      - "-PixelStreamingPort=8888"
      - "-PixelStreamingHideCursor=true"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
    init: true  # If you want init to be enabled for the project service