version: "3"
services:
  
  # The WebRTC TURN server (note that you will need TCP and UDP ports 3478 and 49152-65535 exposed for TURN relaying to function correctly)
  turnserver:
    image: "coturn/coturn:4.5.2"
    network_mode: "host"
    command: ["-a", "-v", "-n", "-u", "user:password", "-p", "3578", "-r", "default-realm", "--no-dtls", "--no-tls"]

  # The Cirrus signalling server
  signalling:
    image: "ghcr.io/epicgames/pixel-streaming-signalling-server:5.1"
    network_mode: "host"
    command:
      - "--publicIp=13.230.92.44"  # Changed from "${PUBLIC_IP}" to the specific IP address
      - "--peerConnectionOptions={\"iceServers\":[{\"urls\": [\"stun:stun.l.google.com:19302\"]}, {\"urls\": [\"turn:13.230.92.44:3478\"], \"username\": \"user\", \"credential\": \"password\"}]}"
    init: true  # Added to match --init in the docker run command
    depends_on:
      - turnserver

  # The Pixel Streaming demo project
  project:
    image: "pixel-streaming-example/project"
    network_mode: "host"
    command:
      - "-RenderOffscreen"
      - "-Windowed"
      - "-ForceRes"
      - "-ResX=1920"
      - "-ResY=1080"
      - "-PixelStreamingIP=13.230.92.44"
      - "-PixelStreamingPort=8888"
      - "-PixelStreamingHideCursor=true"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
