version: "3.8"
services:
  turnserver:
    image: coturn/coturn:4.5.2
    network_mode: host
    command:
      - "-a"
      - "-v"
      - "-n"
      - "-uuser:password"  # Notice no space between -u and the credentials
      - "-p"
      - "3578"
      - "-r"
      - "default-realm"
      - "--no-dtls"
      - "--no-tls"
    init: true

  signalling:
    image: pixel-streaming-signalling-server:latest
    network_mode: host
    command: ["--publicIp=13.230.92.44", "--peerConnectionOptions={ \"iceServers\": [ { \"urls\": [\"stun:stun.l.google.com:19302\"] }, { \"urls\": [\"turn:13.230.92.44:3478\"], \"username\": \"user\", \"credential\": \"password\" } ] }"]
    init: true
    depends_on:
      - turnserver

  project:
    image: pixel-streaming-example/project
    network_mode: host
    command: "-RenderOffscreen -Windowed -ForceRes -ResX=1920 -ResY=1080 -PixelStreamingIP=13.230.92.44 -PixelStreamingPort=8888 -PixelStreamingHideCursor=true"
    init: true
    depends_on:
      - signalling
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
