version: "3"
services:
  
  # The WebRTC TURN server (note that you will need TCP and UDP ports 3478 and 49152-65535 exposed for TURN relaying to function correctly)
  turnserver:
    image: "coturn/coturn:4.5.2"
    network_mode: "host"
    command: ["-a", "-v", "-n", "-u", "user:password", "-p", "${TURN_PORT}", "-r", "default-realm", "--no-dtls", "--no-tls"]

  signalling:
    image: pixel-streaming-signalling-server:latest
    network_mode: host
    command: ["--publicIp=13.230.92.44", "--peerConnectionOptions={ \"iceServers\": [ { \"urls\": [\"stun:stun.l.google.com:19302\"] }, { \"urls\": [\"turn:13.230.92.44:3478\"], \"username\": \"user\", \"credential\": \"password\" } ] }"]
    init: true
    depends_on:
      - turnserver

  # The Pixel Streaming demo project
  project:
    image: "pixel-streaming-example/project:latest"
    network_mode: "host"
    command:
      - "-PixelStreamingURL=ws://127.0.0.1:${STREAMER_PORT}"
    
    depends_on:
      - signalling
    
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
